...

diff --git a/scripts/deploy-prod b/scripts/deploy-prod
--- a/scripts/deploy-prod
+++ b/scripts/deploy-prod
@@ -1,10 +1,15 @@
 USER=ubuntu
-SERVER=141.95.99.38
+SERVER=34.89.169.205
+CURRENT_DIR=$(pwd)
 WORKDIR="attester-client"
+MCC_WORKDIR="mcc"
+MCC_FOLDER="../mcc"
 FNAME=latest-attester-client.tgz
+MCC_FNAME=mcc.tgz
 BACKUPDIR="attester-client-backups"
 CONFIGDIR="attester-client-config"
 BRANCH=main
+MCC_BRANCH=master
 SERVICE=attester-client
 #SERVICE2=attester-client-aggregate
 #SERVICE3=attester-client-trades
@@ -18,15 +23,20 @@ GREENBOLD="${GREEN}$(tput bold)"
 NCNORMAL="${NC}$(tput sgr0)"
 
 # Check if everything is commited localy
-if ! git diff-index --quiet HEAD --; then
-    echo -e "${REDBOLD}Uncommitted changes! Please commit the changes first.${NC}";
-    exit 1;
-fi
+# if ! git diff-index --quiet HEAD --; then
+#     echo -e "${REDBOLD}Uncommitted changes! Please commit the changes first.${NC}";
+#     exit 1;
+# fi
 
 # Check if correct branch
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
   echo -e "${REDBOLD}Wrong branch for deployment: '$CURRENT_BRANCH'. Should be '$BRANCH'.${NC}";
+  exit 1;
+fi
+CURRENT_BRANCH=$(git -C $MCC_FOLDER rev-parse --abbrev-ref HEAD)
+if [[ "$CURRENT_BRANCH" != "$MCC_BRANCH" ]]; then
+  echo -e "${REDBOLD}Wrong branch for deployment: '$CURRENT_BRANCH'. Should be '$MCC_BRANCH'.${NC}";
   exit 1;
 fi
 
@@ -42,8 +52,19 @@ git archive $BRANCH | gzip > tmp_data/$FNAME || { echo 'Archive failed' ; exit 1
 echo -e "${GREENBOLD}Archiving done.${NC} Copying to server ..."
 scp tmp_data/$FNAME $USER@$SERVER:~ || { echo 'sco failed' ; exit 1; }
 
+
+# Copy MCC
+echo -e "${GREENBOLD}Copying MCC ..."
+cd $MCC_FOLDER
+mkdir -p tmp_data
+git archive $MCC_BRANCH | gzip > tmp_data/$MCC_FNAME || { echo 'Archive failed' ; exit 1; }
+scp tmp_data/$MCC_FNAME $USER@$SERVER:~ || { echo 'sco failed' ; exit 1; }
+cd $CURRENT_DIR
+
+
 # Crete install folder if they do not exist
 ssh -n $USER@$SERVER "mkdir -p $WORKDIR; mkdir -p $WORKDIR-config; mkdir -p $WORKDIR-backups;"
+ssh -n $USER@$SERVER "mkdir -p $MCC_WORKDIR"
 
 # Do the following:
 # - Clean $WORKDIR. 
@@ -53,21 +74,30 @@ ssh -n $USER@$SERVER "mkdir -p $WORKDIR; mkdir -p $WORKDIR-config; mkdir -p $WOR
 echo -e "${GREENBOLD}Copying to server done.${NC} Installing ..."
 ssh -n $USER@$SERVER "rm -rf $WORKDIR/*; mv $FNAME $WORKDIR; cd $WORKDIR; tar xzf $FNAME; mv $FNAME ../$BACKUPDIR/deploy--$(date +\"%Y-%m-%d--%H-%M-%S\").tgz" || { echo 'Remote deployment failed' ; exit 1; }
 
+ssh -n $USER@$SERVER "rm -rf $MCC_WORKDIR/*; mv $MCC_FNAME $MCC_WORKDIR; cd $MCC_WORKDIR; tar xzf $MCC_FNAME; mv $MCC_FNAME ../$BACKUPDIR/mcc-deploy--$(date +\"%Y-%m-%d--%H-%M-%S\").tgz" || { echo 'Remote deployment failed' ; exit 1; }
+
 # echo -e "${GREENBOLD}Initializing configuration${NC} Installing ..."
 ssh -n $USER@$SERVER "cp $CONFIGDIR/.env $WORKDIR;" || { echo 'Remote deployment failed' ; exit 1; }
 
+# Build the MCC.
+echo -e "${GREENBOLD}Installing MCC.${NC} Running yarn ..."
+ssh -n $USER@$SERVER "source .profile; cd $MCC_WORKDIR; yarn; yarn build; yarn link" || { echo 'yarn install failed' ; exit 1; }
+
 # Run yarn in $WORKDIR 
 echo -e "${GREENBOLD}Installing done.${NC} Running yarn ..."
-ssh -n $USER@$SERVER "source .profile; cd $WORKDIR; yarn" || { echo 'yarn install failed' ; exit 1; }
+ssh -n $USER@$SERVER "source .profile; cd $WORKDIR; yarn link flare-mcc; yarn" || { echo 'yarn install failed' ; exit 1; }
 
 # Build the app.
 echo -e "${GREENBOLD}Yarn install done.${NC} Building app ... "
 ssh -n $USER@$SERVER "source .profile; cd $WORKDIR; yarn build" || { echo 'Building app failed' ; exit 1; }
 
+
+
+
 # Restart the app as a service.
 echo -e "${GREENBOLD}Build successful.${NC} Restarting app"
-ssh -n $USER@$SERVER "systemctl --user restart $SERVICE" || { echo 'Restarting collector failed' ; exit 1; }
-ssh -n $USER@$SERVER "systemctl --user restart $SERVICE2" || { echo 'Restarting aggregator failed' ; exit 1; }
-ssh -n $USER@$SERVER "systemctl --user restart $SERVICE3" || { echo 'Restarting backend failed' ; exit 1; }
-ssh -n $USER@$SERVER "systemctl --user restart $SERVICE4" || { echo 'Restarting exchanges failed' ; exit 1; }
+#ssh -n $USER@$SERVER "systemctl --user restart $SERVICE" || { echo 'Restarting collector failed' ; exit 1; }
+#ssh -n $USER@$SERVER "systemctl --user restart $SERVICE2" || { echo 'Restarting aggregator failed' ; exit 1; }
+#ssh -n $USER@$SERVER "systemctl --user restart $SERVICE3" || { echo 'Restarting backend failed' ; exit 1; }
+#ssh -n $USER@$SERVER "systemctl --user restart $SERVICE4" || { echo 'Restarting exchanges failed' ; exit 1; }
 echo -e "${GREENBOLD}Done.${NC}"
